---

- hosts: node1
  become: true
  become_method: sudo
  roles:
    - base
  tasks:
  - include: tasks/prepare_pc_enablemane.yml

#  - name: print stdout
#    debug:
#      msg: "{{ result.stdout }}"
