---
- name: "APT - Add Docker GPG key"
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "APT - Add Docker repository"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: "APT - install misc packages"
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
    - "aptitude"
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: "APT - install 'docker-ce'"
  become: yes
  apt:
    name: "docker-ce"
    update_cache: yes
- name: pull ubuntu docker image
  become: yes
  shell: docker pull ubuntu || true

- name: add remote user to docker group
  become: yes
  shell: usermod -aG docker "{{ ansible_ssh_user }}"
